### ISSUE TITLE
Stability Test question

### ISSUE THREAD

**Issue by zihuuuu** [tengyu-liu/GenDexGrasp#10]
when I run python run_grasp_test.py --robot_name=shadowhand --dataset=SqrtUnseenShadowhand-SharpClamp_A3 --domain=ood --base_name=align_dist --comment=example,The following error will be reported, how to solve these problems.
Failed to load 'envs/assets/franka_description/robots/movable_dexterous_hand_new.urdf'[Error] [carb.gym.plugin] Failed to parse URDF file 'franka_description/robots/movable_dexterous_hand_new.urdf'
[Error] [carb.gym.plugin] Failed to import URDF file 'franka_description/robots/movable_dexterous_hand_new.urdf'
[Error] [carb.gym.plugin] *** Failed to load 'franka_description/robots/movable_dexterous_hand_new.urdf' from 'envs/assets'
Enumerating envs::   0%|                                       | 0/64 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "run_grasp_test.py", line 177, in <module>
    isaac_model = IsaacGraspTestForce(cfg, sim_params, gymapi.SIM_PHYSX, "cuda", 0, headless=sim_headless,
  File "/home/czl/GenDexGrasp2/envs/tasks/grasp_test_force_shadowhand.py", line 95, in __init__
    super().__init__(cfg=self.cfg, enable_camera_sensors=cfg["env"]["enableCameraSensors"],
  File "/home/czl/GenDexGrasp2/envs/tasks/base_task.py", line 81, in __init__
    self.create_sim()
  File "/home/czl/GenDexGrasp2/envs/tasks/grasp_test_force_shadowhand.py", line 338, in create_sim
    self._place_agents(
  File "/home/czl/GenDexGrasp2/envs/tasks/grasp_test_force_shadowhand.py", line 636, in _place_agents
    self._load_agent(env_ptr, env_id)
  File "/home/czl/GenDexGrasp2/envs/tasks/grasp_test_force_shadowhand.py", line 397, in _load_agent
    dexterous_dof_state["pos"] = default_dof_pos
ValueError: could not broadcast input array from shape (30,) into shape (0,)

**Comment by jmchumbo** [comment]
Greetings!

I have encountered the same issue you are currently facing.

To resolve the problem, modify line 346 in the file grasp_test_force_shadowhand.py as follows:

Change:

dexterous_asset_file = "franka_description/robots/movable_dexterous_hand_new.urdf"

To:


dexterous_asset_file = "movable_hand_urdf/RH8DL/robots/movable_shadowhand.urdf"

Hope it works!

**Comment by Xiaoyao-Li** [comment]
Thanks the reply by @jmchumbo .

It seems like you fail to load the urdf file, please make sure the file is correct and be placed at the correct path.
